### ISSUE TITLE
Syntax for multiple deployment targets

### ISSUE THREAD

**Issue by Starraider** [mittwald/deployer-recipes#25]
In many projects, it is common to have a separate staging server and production server.
Until now, I have always solved this in Deployer:
```php
host('live')
    ->hostname('pxxxxx.mittwaldserver.info')
    ->user('pxxxxx')
    ->set('branch', 'main')
   ...
host('staging')
    ->hostname('pyyyyy.mittwaldserver.info')
    ->user('pyyyyy')
    ->set('branch', 'develop')
   ...
```
This way you could easily choose, if you want to deploy to the live or staging server by `/vendor/bin/dep deploy live`

With your Mittwald deployer-recipes, however, it is not clear to me what the syntax must look like here in order to be able to distinguish between two servers!
How can I set different "names" for the servers in the `mittwald_app('<app-id>')`?

**Comment by martin-helmich** [comment]
In this case, I'd recommend creating two separate apps for each environment (staging+prod), which may or may not run within the same project.

You probably won't be able to use the `mittwald_app` shorthand function in this case (because it hardcodes the hostname to `mittwald` -- something that we could actually make configurable, now that I think about it 🤔), since deployer will then treat those as a single host. Instead, you can still define the hosts using the regular `host(...)` function, and then set the `mittwald_app_id` variable for each host.

```php
host('mittwald-prod')
    ->set('mittwald_app_id', '<app-id-prod>')
    ->set('branch', 'main');

host('mittwald-staging')
    ->set('mittwald_app_id', '<app-id-staging>')
    ->set('branch', 'develop');
```

Let me know if that helps!

**Comment by martin-helmich** [comment]
Quick update: With #33, you now have the option to overwrite the hostname when using the  `mittwald_app` shorthand function:

```php
mittwald_app('<app-id-prod>', hostname: 'mittwald-prod')
    ->set('branch', 'main');
mittwald_app('<app-id-staging>', hostname: 'mittwald-staging')
    ->set('branch', 'develop');
```

I've also added a short section on deploying to multiple environments in the respective documentation: https://github.com/mittwald/developer-portal/pull/62.

I hope that helps; I'll close this issue for now -- feel free to reopen. 🙂
